version: "3.7"

services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: cybergenix
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_LOG_LEVEL=${APP_LOG_LEVEL}
      - APP_URL=${APP_URL}
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    depends_on:
      - mysql
      - redis
      - mailpit
      - nginx
      - phpmyadmin

  mysql:
    image: mysql:latest
    container_name: cybergenix-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./compose-dev/mysql/data:/var/lib/mysql
    networks:
      - laravel

  php:
    image: php:fpm-bullseye
    container_name: cybergenix-php
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/html
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: cybergenix-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./compose-dev/nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: cybergenix-phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - laravel

  mailpit:
    image: axllent/mailpit:latest
    container_name: cybergenix-mailpit
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      - MAIL_MAILER=${MAIL_MAILER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: cybergenix-redis
    restart: unless-stopped
    volumes:
      - ./compose-dev/redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
